[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[invariant]
runs = 128
depth = 128
fail_on_revert = true